<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU_Test" Id="{625ea067-90fc-4ae7-8747-07e5ccfd8513}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_Test
VAR
	fbFileHandle_Test: FileHandle_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>